export const PORT = 'PORT';
export const NODE_ENV = 'NODE_ENV';

export const JWT_SECRET = 'JWT_SECRET';
export const JWT_EXPIRES_IN = 'JWT_EXPIRES_IN';
export const JWT_MAIL_VERIFICATION_SECRET = 'JWT_MAIL_VERIFICATION_SECRET';
export const JWT_MAIL_VERIFICATION_EXPIRES_IN =
  'JWT_MAIL_VERIFICATION_EXPIRES_IN';

export const MAIL_HOST = 'MAIL_HOST';
export const MAIL_PORT = 'MAIL_PORT';
export const MAIL_SECURE = 'MAIL_SECURE';
export const MAIL_USER = 'MAIL_USER';
export const MAIL_PASS = 'MAIL_PASS';
export const MAIL_FROM = 'MAIL_FROM';

export const PROFILE_EXTRACTION_API_URL = 'PROFILE_EXTRACTION_API_URL';
export const PROFILE_EXTRACTION_API_KEY = 'PROFILE_EXTRACTION_API_KEY';

export const CLIENT_URL = 'CLIENT_URL';

export const GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID';
